"""Initial migration

Revision ID: bffd764276e9
Revises: 
Create Date: 2025-09-17 11:03:33.392262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bffd764276e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=80), nullable=True),
    sa.Column('visited_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visit')
    # ### end Alembic commands ###
